name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - v*
  pull_request:
    branches:
      - master
      - main
      - v*

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GOLANGCI_LINT_VERSION: "v2.9.0"
    steps:

      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Check Go dependency minimum age
        run: |
          go install github.com/fchimpan/gomod-age@09005169a4792ad1a4824e1fc6d85785d91cea36
          gomod-age

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Test
        run: |
          make test-race
